### ISSUE TITLE
Possibility for adding GFPGAN ?

### ISSUE THREAD

**Issue by zecretaccount** [mike9251/simswap-inference-pytorch#9]
like here? 
https://github.com/neuralchen/SimSwap/issues/259

**Comment by DrBlou** [comment]
Hello, yes please I would love to see this update on your release

**Comment by zecretaccount** [comment]
Just tried GFPGAN on its own and god damn it is god. Just need to do the same thing as in the link and that would be awesome :D

**Comment by DrBlou** [comment]
Yes I am using it with the original simswap code and the results are amazing. 
But it's not using my GPU  the proper way (10 15% used / 1.5-2it/s). 
With this repo my GPU is used by 35 - 45% (RTX 3080) 5 - 7 its/s. The only thing is that is not implementing GFPGAN . I tried to implement the code myself but my skills are very limited .. 

[https://github.com/neuralchen/SimSwap/issues/259#:~:text=fitzgeraldja-,commented%20on%20Sep%2030,-%40epicstar7%20you%20can](url)  

It would be very nice if someone can implement the code in the above comment to this repo.

**Comment by mike9251** [comment]
Hey guys! Thanks for the suggestion, I think it would be a great addition to the app as an optional post processing step. I'll take a look at it.

**Comment by DrBlou** [comment]
Thanks Mike :)  Can't wait to see the results !

**Comment by mike9251** [comment]
It turned out that adding gfpgan support was easier than I expected, here are results for comparison
with gfpgan 
![swap_multi_people_1](https://user-images.githubusercontent.com/25375369/206865862-fd04b24a-0afd-44ab-9258-2c3513c7f9c7.jpg)
without
![swap_multi_people_0](https://user-images.githubusercontent.com/25375369/206865861-19b95389-1162-4b9d-9455-7236c41ed092.jpg)

**Comment by DrBlou** [comment]
Oww man, very nice ! You're a boss, thank you !

**Comment by DrBlou** [comment]
Its working fine in anaconda command prompt, but when I launch the web app, it returns this error : 

![image](https://user-images.githubusercontent.com/92190077/206869645-66c46cb9-b7a9-4597-87f3-34e67df11f39.png)


Can you take a look at it please ? 

Thanks in advance


```
C:\Users\Blue\.conda\envs\simswapgpu\lib\site-packages\torch\serialization.py:779: UserWarning: 'torch.load' received a zip file that looks like a TorchScript archive dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to silence this warning)
  warnings.warn("'torch.load' received a zip file that looks like a TorchScript archive"
C:\Users\Blue\.conda\envs\simswapgpu\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3191.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
2022-12-10 19:30:52.560 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Blue\.conda\envs\simswapgpu\lib\site-packages\streamlit\runtime\legacy_caching\caching.py", line 589, in get_or_create_cached_value
    return_value = _read_from_cache(
  File "C:\Users\Blue\.conda\envs\simswapgpu\lib\site-packages\streamlit\runtime\legacy_caching\caching.py", line 349, in _read_from_cache
    raise e
  File "C:\Users\Blue\.conda\envs\simswapgpu\lib\site-packages\streamlit\runtime\legacy_caching\caching.py", line 334, in _read_from_cache
    return _read_from_mem_cache(
  File "C:\Users\Blue\.conda\envs\simswapgpu\lib\site-packages\streamlit\runtime\legacy_caching\caching.py", line 252, in _read_from_mem_cache
    raise CacheKeyNotFoundError("Key not found in mem cache")
streamlit.runtime.legacy_caching.caching.CacheKeyNotFoundError: Key not found in mem cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Blue\.conda\envs\simswapgpu\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 563, in _run_script
    exec(code, module.__dict__)
  File "C:\content\Simswapgpu\app_web.py", line 145, in <module>
    model = load_model(config)
  File "C:\Users\Blue\.conda\envs\simswapgpu\lib\site-packages\streamlit\runtime\legacy_caching\caching.py", line 623, in wrapped_func
    return get_or_create_cached_value()
  File "C:\Users\Blue\.conda\envs\simswapgpu\lib\site-packages\streamlit\runtime\legacy_caching\caching.py", line 607, in get_or_create_cached_value
    return_value = non_optional_func(*args, **kwargs)
  File "C:\content\Simswapgpu\app_web.py", line 105, in load_model
    return SimSwap(
  File "c:\content\Simswapgpu\src\simswap.py", line 110, in __init__
    if config.enhance_output:
AttributeError: 'Config' object has no attribute 'enhance_output'
```

**Comment by mike9251** [comment]
Done

**Comment by DrBlou** [comment]
Thanks for your work

**Comment by zecretaccount** [comment]
AWESOME!
Thanks Mike!!
